name: BarrelShop
version: 0.0.1-beta1
main: mc.barrelshop.PluginMain
api-version: 1.20
softdepend:
  - Compendium

#

commands: {}

#

permissions:
  mc.barrelshop.*:
    description: ''
    children:
      mc.barrelshop.shop.*: true

  #

  mc.barrelshop.shop.*:
    description: ''
    children:
      mc.barrelshop.shop.admin.*: true
      mc.barrelshop.shop.self.*: true
      mc.barrelshop.shop.others.*: true

  #

  mc.barrelshop.shop.admin.*:
    description: ''
    children:
      mc.barrelshop.shop.admin.create: true
      mc.barrelshop.shop.admin.delete: true
      mc.barrelshop.shop.admin.manage: true

  mc.barrelshop.shop.admin.create:
    description: 'Allows to create admin shops.'
    default: false

  mc.barrelshop.shop.admin.delete:
    description: 'Allows to delete admin shops.'
    default: false

  mc.barrelshop.shop.admin.manage:
    description: 'Allows to manage admin shops.'
    default: false

  #

  mc.barrelshop.shop.self.*:
    description: ''
    children:
      mc.barrelshop.shop.self.create: true
      mc.barrelshop.shop.self.delete: true
      mc.barrelshop.shop.self.manage: true

  mc.barrelshop.shop.self.create:
    description: 'Allows to create its own shops.'
    default: true

  mc.barrelshop.shop.self.delete:
    description: 'Allows to delete its own shops.'
    default: true

  mc.barrelshop.shop.self.manage:
    description: 'Allows to manage its own shops.'
    default: true

  #

  mc.barrelshop.shop.others.*:
    description: ''
    children:
      mc.barrelshop.shop.others.delete: true
      mc.barrelshop.shop.others.manage: true

  mc.barrelshop.shop.others.delete:
    description: 'Allows to delete other players shops.'
    default: false

  mc.barrelshop.shop.others.manage:
    description: 'Allows to manage other players shops.'
    default: false