name: release-build
run-name: ''
on: [workflow_dispatch]
jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: ./gradlew clean build --warning-mode=all -Prelease-build --refresh-dependencies

      - name: publish release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/